version: "3.1"

services:
  backend:
    build: ./backend
    hostname: backend
    expose:
      - "5000"
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - DATABASE_URI=mongodb
    networks:
      - microservices

  mongodb:
    image: mongo:latest
    expose:
      - "27017"
    ports:
      - 27017:27017
    networks:
      - microservices

  frontend:
    build: ./frontend
    hostname: frontend
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5000
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
